import os


from config.settings import get_config, AppConfig

config = get_config()




# 获取项目根目录路径
PROJECT_ROOT = config.PROJECT_ROOT
DATA_DIR = config.DATA_DIR
RAW_DATA_DIR = config.RAW_DATA_DIR
MODELS_DATA_DIR = config.MODELS_DATA_DIR
PROCESSED_DATA_DIR = config.PROCESSED_DATA_DIR


# 共享模型存放文件夹
SHARED_DATA_DIR = config.SHARED_DATA_DIR
# 基本模型
CHINESE_MAC_BERT_BASE_NAME = config.base_models.chinese_mac_bert
BGE_SMALL_ZH_NAME = config.base_models.bge_small_zh

# 小说-人物识别模型
PERSON_RECOGNITION_CHINESE_MAC_BERT_NAME = config.PERSON_MODEL_NAME
# 小说-关系抽取模型
RELATION_RECOGNITION_CHINESE_MAC_BERT_NAME = config.RELATION_MODEL_NAME
# 小说-文本分类模型
TEXT_RECOGNITION_CHINESE_MAC_BERT_NAME = config.TEXT_MODEL_NAME


# 人工训练数据
MANUAL_DATA_DIR = os.path.join(PROCESSED_DATA_DIR, config.training.manual_dir)
PERSON_TRAIN_NAME= config.training.files.person_train
RELATION_TRAIN_NAME= config.training.files.relation_train
TEXT_TRAIN_NAME= config.training.files.text_train

# 训练模型验证集数据
VALIDATION_DATA_DIR = os.path.join(MANUAL_DATA_DIR, config.training.validation_dir)
PERSON_VALIDATION_NAME= config.training.files.person_validation
RELATION_VALIDATION_NAME= config.training.files.relation_validation
TEXT_VALIDATION_NAME= config.training.files.text_validation



# 自动标注数据
AUTO_DATA_DIR = os.path.join(PROCESSED_DATA_DIR, config.training.auto_dir)
AUTO_PERSON_MARGINALIA_NAME = config.training.files.auto_person
AUTO_RELATION_MARGINALIA_NAME = config.training.files.auto_relation
AUTO_TEXT_MARGINALIA_NAME= config.training.files.auto_text

# 评估模型
APPRAISE_DATA_DIR = os.path.join(PROCESSED_DATA_DIR, config.training.appraise_dir)
APPRAISE_PERSON_DATA_NAME = config.training.files.appraise_person
APPRAISE_RELATION_DATA_NAME = config.training.files.appraise_relation
APPRAISE_TEXT_DATA_NAME = config.training.files.appraise_text



#========Chroma/Graph系统配置信息=============
SPLITS_DATA_DIR = os.path.join(PROCESSED_DATA_DIR, config.SPLITS_DATA_DIR)
CHROMA_DOCUMENT_DATA = config.CHROMA_DOCUMENT_DATA  # 向量数据库文档 数据文件名称
CHROMA_VECTRO_SEGMENT_DATA = config.CHROMA_SEGMENT_DATA  # 向量数据库语义索引 数据文件名称
GRAPH_SEGMENT_DATA = config.GRAPH_SEGMENT_DATA # 知识图谱 数据文件名称
#向量数据库与集合名称
VECTOR_DATABASES_DATA_DIR = os.path.join(DATA_DIR, config.VECTOR_DATABASES_DATA_DIR)
CHROMA_DOCUMENT_COLLECTION = config.CHROMA_DOCUMENT_COLLECTION       # 向量数据库文档 集合名称
CHROMA_SEGMENT_COLLECTION = config.CHROMA_SEGMENT_COLLECTION   # 向量数据库语义索引 集合名称


"""
 小说文章采样基本配置
"""
# 采样配置
SAMPLING_CONFIG = config.SAMPLING_CONFIG

#大模型
DEEPSEEK_API_KEY= config.DEEPSEEK_API_KEY
DEEPSEEK_URL = config.DEEPSEEK_URL

# Neo4j 配置
NEO4J_URL = config.NEO4J_URL
NEO4J_USER = config.NEO4J_USER
NEO4J_PASSWORD = config.NEO4J_PASSWORD

# 魔塔配置
MODELSCOPE_ACCESS_TOKEN = config.MODELSCOPE_ACCESS_TOKEN
MODELSCOPE_CACHE_DIR = config.MODELSCOPE_CACHE_DIR


# 导出函数
__all__ = [
    'PROJECT_ROOT', 'DATA_DIR', 'RAW_DATA_DIR', 'PROCESSED_DATA_DIR',
    'MODELS_DATA_DIR', 'VECTOR_DATABASES_DATA_DIR', 'SPLITS_DATA_DIR',
    'SHARED_DATA_DIR',
    'PERSON_RECOGNITION_CHINESE_MAC_BERT_NAME',
    'RELATION_RECOGNITION_CHINESE_MAC_BERT_NAME',
    'TEXT_RECOGNITION_CHINESE_MAC_BERT_NAME',
    'CHINESE_MAC_BERT_BASE_NAME', 'BGE_SMALL_ZH_NAME',
    'MANUAL_DATA_DIR', 'VALIDATION_DATA_DIR', 'AUTO_DATA_DIR', 'APPRAISE_DATA_DIR',
    'PERSON_TRAIN_NAME', 'RELATION_TRAIN_NAME', 'TEXT_TRAIN_NAME',
    'PERSON_VALIDATION_NAME','RELATION_VALIDATION_NAME','TEXT_VALIDATION_NAME',
    'AUTO_PERSON_MARGINALIA_NAME','AUTO_RELATION_MARGINALIA_NAME','AUTO_TEXT_MARGINALIA_NAME',
    'APPRAISE_PERSON_DATA_NAME','APPRAISE_RELATION_DATA_NAME','APPRAISE_TEXT_DATA_NAME',
    'CHROMA_DOCUMENT_DATA', 'CHROMA_VECTRO_SEGMENT_DATA', 'GRAPH_SEGMENT_DATA',
    'CHROMA_DOCUMENT_COLLECTION', 'CHROMA_SEGMENT_COLLECTION',
    'SAMPLING_CONFIG',
    'DEEPSEEK_API_KEY', 'DEEPSEEK_URL',
    'NEO4J_URL', 'NEO4J_USER', 'NEO4J_PASSWORD',
    'MODELSCOPE_ACCESS_TOKEN', 'MODELSCOPE_CACHE_DIR',
    'get_config', 'AppConfig'
]

